apiVersion: v1
kind: Pod
metadata:
  namespace: env-setup
  name: app
spec:
  containers:
    - name: app-container
      image: busybox
      command:
        [
          "sh",
          "-c",
          "echo ${WHERE}: ${MEAL} = ${INGREDIENT_1} + ${INGREDIENT_2} + ${INGREDIENT_3} && sleep 60",
        ]
      env:
        - name: MEAL
          value: Pizza
        - name: INGREDIENT_2
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ingredient
        - name: INGREDIENT_3
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: ingredient
        - name: WHERE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      envFrom:
        - configMapRef:
            name: env-app-config
